# Generated by Django 5.1.3 on 2025-04-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartaoCidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Morada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=120)),
                ('cp', models.CharField(max_length=120)),
                ('porta', models.CharField(max_length=120)),
                ('apt', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UFCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.cartaocidadao')),
                ('morada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.morada')),
                ('ufcd', models.ManyToManyField(to='myApp.ufcd')),
            ],
        ),
    ]
